/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "passwd.h"

bool_t
xdr_Password (XDR *xdrs, Password *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->text, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response (XDR *xdrs, Response *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, 100))
		 return FALSE;
	return TRUE;
}
