/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PASSWD_H_RPCGEN
#define _PASSWD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Password {
	char *text;
};
typedef struct Password Password;

struct Response {
	bool_t success;
	char *message;
};
typedef struct Response Response;

#define PASSWD_PROG 0x31234567
#define PASSWD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CHECK_PASSWORD 1
extern  Response * check_password_1(Password *, CLIENT *);
extern  Response * check_password_1_svc(Password *, struct svc_req *);
extern int passwd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CHECK_PASSWORD 1
extern  Response * check_password_1();
extern  Response * check_password_1_svc();
extern int passwd_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Password (XDR *, Password*);
extern  bool_t xdr_Response (XDR *, Response*);

#else /* K&R C */
extern bool_t xdr_Password ();
extern bool_t xdr_Response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PASSWD_H_RPCGEN */
