/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "datetime.h"

bool_t
xdr_date_time (XDR *xdrs, date_time *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->datetime, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_year_info (XDR *xdrs, year_info *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->year))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_system_info (XDR *xdrs, system_info *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->info, 256))
		 return FALSE;
	return TRUE;
}
