/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATETIME_H_RPCGEN
#define _DATETIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date_time {
	char *datetime;
};
typedef struct date_time date_time;

struct year_info {
	int year;
};
typedef struct year_info year_info;

struct system_info {
	char *info;
};
typedef struct system_info system_info;

#define DATETIMEINFO_PROG 0x23451111
#define DATETIMEINFO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_DATETIME 1
extern  date_time * get_datetime_1(void *, CLIENT *);
extern  date_time * get_datetime_1_svc(void *, struct svc_req *);
#define GET_YEAR 2
extern  year_info * get_year_1(void *, CLIENT *);
extern  year_info * get_year_1_svc(void *, struct svc_req *);
#define GET_SYSINFO 3
extern  system_info * get_sysinfo_1(void *, CLIENT *);
extern  system_info * get_sysinfo_1_svc(void *, struct svc_req *);
extern int datetimeinfo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_DATETIME 1
extern  date_time * get_datetime_1();
extern  date_time * get_datetime_1_svc();
#define GET_YEAR 2
extern  year_info * get_year_1();
extern  year_info * get_year_1_svc();
#define GET_SYSINFO 3
extern  system_info * get_sysinfo_1();
extern  system_info * get_sysinfo_1_svc();
extern int datetimeinfo_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date_time (XDR *, date_time*);
extern  bool_t xdr_year_info (XDR *, year_info*);
extern  bool_t xdr_system_info (XDR *, system_info*);

#else /* K&R C */
extern bool_t xdr_date_time ();
extern bool_t xdr_year_info ();
extern bool_t xdr_system_info ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATETIME_H_RPCGEN */
