/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEXTPROC_H_RPCGEN
#define _TEXTPROC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Paragraph {
	char *text;
};
typedef struct Paragraph Paragraph;

struct Result {
	int words;
	int lines;
	int characters;
};
typedef struct Result Result;

#define TEXTPROC_PROG 0x23451111
#define TEXTPROC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROCESS_PARAGRAPH 1
extern  Result * process_paragraph_1(Paragraph *, CLIENT *);
extern  Result * process_paragraph_1_svc(Paragraph *, struct svc_req *);
extern int textproc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROCESS_PARAGRAPH 1
extern  Result * process_paragraph_1();
extern  Result * process_paragraph_1_svc();
extern int textproc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Paragraph (XDR *, Paragraph*);
extern  bool_t xdr_Result (XDR *, Result*);

#else /* K&R C */
extern bool_t xdr_Paragraph ();
extern bool_t xdr_Result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEXTPROC_H_RPCGEN */
