/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "textproc.h"

bool_t
xdr_Paragraph (XDR *xdrs, Paragraph *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->text, 10000))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Result (XDR *xdrs, Result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->words))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lines))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->characters))
		 return FALSE;
	return TRUE;
}
