/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "textproc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Result *
process_paragraph_1(Paragraph *argp, CLIENT *clnt)
{
	static Result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PROCESS_PARAGRAPH,
		(xdrproc_t) xdr_Paragraph, (caddr_t) argp,
		(xdrproc_t) xdr_Result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
